@baseUrl = http://localhost:8080

### Valid request
PUT {{baseUrl}}/phones/alice
Content-Type: application/json

{
  "phone": "380950000000"
}

> {%
    client.test("Valid request", function () {
        client.assert(response.status === 204);
    });
%}

### Invalid request
PUT {{baseUrl}}/phones/bob
Content-Type: application/json

{
  "phone": "+380950000000"
}

> {%
    client.test("Invalid request", function () {
        client.assert(response.status === 400);
    });
%}

### Valid response
GET {{baseUrl}}/phones/alice
Content-Type: application/json

> {%
    client.test("Valid request", function () {
        client.assert(response.status === 200);
    });
%}

### Invalid response
GET {{baseUrl}}/phones/bob
Content-Type: application/json

> {%
    client.test("Valid request", function () {
        client.assert(response.status === 500);
    });
%}
